package org.iets3.req.core.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.IconResource;

public class IconContainer {
  protected static IconResource RESOURCE_a0a0a = new IconResource("req.png", IconContainer.class);
  protected static IconResource RESOURCE_a0a0j = new IconResource("addChild.png", IconContainer.class);
  protected static IconResource RESOURCE_a0a0k = new IconResource("addSibling.png", IconContainer.class);
  protected static IconResource RESOURCE_a0a0l = new IconResource("delete.png", IconContainer.class);
  protected static IconResource RESOURCE_a0a0x = new IconResource("reqchunk.png", IconContainer.class);
}
