package org.iets3.glossary.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.IconResource;

public class IconContainer {
  protected static IconResource RESOURCE_a0a0e = new IconResource("glossary2.png", IconContainer.class);
}
