package org.iets3.req.plugin.plugin;

/*Generated by MPS */

import jetbrains.mps.plugins.actions.GeneratedActionGroup;
import com.intellij.openapi.actionSystem.Separator;

public class Group_requirementsAsTablesDetails_ActionGroup extends GeneratedActionGroup {
  public static final String ID = "org.iets3.req.plugin.plugin.Group_requirementsAsTablesDetails_ActionGroup";
  public Group_requirementsAsTablesDetails_ActionGroup() {
    super("Group_requirementsAsTablesDetails", ID);
    this.setIsInternal(false);
    this.setPopup(false);
    Group_requirementsAsTablesDetails_ActionGroup.this.add(new TogglerequirementsAsTablesDetails());
    Group_requirementsAsTablesDetails_ActionGroup.this.add(Separator.getInstance());
  }
}
