package org.iets3.req.plugin.plugin;

/*Generated by MPS */

import javax.swing.Icon;
import jetbrains.mps.util.IconUtil;

public class IconContainer {
  protected static Icon ICON_a0 = IconUtil.getIcon("req.png");
  protected static Icon ICON_a0_0 = IconUtil.getIcon("delete.png");
  protected static Icon ICON_a0_1 = IconUtil.getIcon("reqchunk.png");
}
