package org.iets3.req.plugin.plugin;

/*Generated by MPS */

import com.mbeddr.mpsutil.projectview.runtime.IProjectViewDescriptor;
import java.util.List;
import com.mbeddr.mpsutil.projectview.runtime.IViewDescriptor;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import java.util.ArrayList;
import com.mbeddr.mpsutil.projectview.runtime.AbstractViewDescriptor;
import java.util.Map;
import com.mbeddr.mpsutil.projectview.runtime.ElementId;
import com.mbeddr.mpsutil.projectview.runtime.IViewElementDescriptor;
import jetbrains.mps.internal.collections.runtime.MapSequence;
import java.util.LinkedHashMap;
import com.mbeddr.mpsutil.projectview.runtime.AbstractViewElementDescriptor;
import org.jetbrains.mps.openapi.model.SNode;
import com.mbeddr.mpsutil.projectview.runtime.ViewId;
import com.mbeddr.mpsutil.projectview.runtime.ViewElement;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import jetbrains.mps.project.Project;
import org.jetbrains.mps.openapi.model.SModel;
import jetbrains.mps.internal.collections.runtime.Sequence;
import jetbrains.mps.internal.collections.runtime.IWhereFilter;
import jetbrains.mps.internal.collections.runtime.ISelector;
import org.jetbrains.annotations.Nullable;
import javax.swing.Icon;
import jetbrains.mps.ide.icons.IconManager;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;

public class ProjectViewDescriptor implements IProjectViewDescriptor {
  public static ProjectViewDescriptor INSTANCE = new ProjectViewDescriptor();

  private List<IViewDescriptor> myViews = ListSequence.fromList(new ArrayList<IViewDescriptor>());

  public ProjectViewDescriptor() {
    ListSequence.fromList(myViews).addElement(new AbstractViewDescriptor() {
      private Map<ElementId, IViewElementDescriptor> myElements = MapSequence.fromMap(new LinkedHashMap<ElementId, IViewElementDescriptor>(16, (float) 0.75, false));

      {
        addElement(new AbstractViewElementDescriptor<SNode>() {
          @Override
          public ElementId getExtendsId() {
            return new ElementId("root", new ViewId("org.iets3.core.plugin.plugin.SpecExplorer"));
          }
          @Override
          public ElementId getParentId() {
            return new ElementId("specModel", new ViewId("org.iets3.core.plugin.plugin.SpecExplorer"));
          }
          @Override
          public String getLabel(ViewElement element) {
            return SPropertyOperations.getString(((SNode) element.getObject(new ElementId("requirementsModule", new ViewId("org.iets3.req.plugin.plugin.RequirementsExplorer")))), MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"));
          }
          @Override
          public boolean isAbstract() {
            return false;
          }
          @Override
          public boolean isOverride() {
            return false;
          }
          @Override
          public Iterable<ViewElement<SNode>> queryElements(final Project mpsProject, final ViewElement parentElement, final ViewId contextView) {
            final ElementId descriptorId = new ElementId("requirementsModule", new ViewId("org.iets3.req.plugin.plugin.RequirementsExplorer"));
            ViewElement element = parentElement;
            Object queryResult = RequirementsExplorerHelper.getReqChunks(((SModel) element.getObject(new ElementId("specModel", new ViewId("org.iets3.core.plugin.plugin.SpecExplorer")))));

            Iterable<SNode> rawSequence = (queryResult instanceof Iterable ? ((Iterable<SNode>) queryResult) : Sequence.<SNode>singleton(((SNode) queryResult)));

            return Sequence.fromIterable(rawSequence).where(new IWhereFilter<SNode>() {
              public boolean accept(SNode it) {
                return it != null;
              }
            }).select(new ISelector<SNode, ViewElement<SNode>>() {
              public ViewElement<SNode> select(SNode it) {
                return new ViewElement<SNode>(it, descriptorId, mpsProject, parentElement, contextView);
              }
            });
          }
          @Override
          public ElementId getId() {
            return new ElementId("requirementsModule", new ViewId("org.iets3.req.plugin.plugin.RequirementsExplorer"));
          }
          @Nullable
          @Override
          public Icon getIcon(ViewElement element) {
            return IconManager.getIconFor(((SNode) element.getObject(new ElementId("requirementsModule", new ViewId("org.iets3.req.plugin.plugin.RequirementsExplorer")))));
          }
          @Override
          public String getActionGroupId(ViewElement element) {
            return reqActions_ActionGroup.ID;
          }
          @Override
          public boolean isAssignable(Project mpsProject, ViewElement<SNode> element) {
            return super.isAssignable(mpsProject, element) && SNodeOperations.isInstanceOf(element.getObject(), MetaAdapterFactory.getConcept(0xa3c6f64241b744cbL, 0x951b463b8427a245L, 0x477d8ab2bc81949cL, "org.iets3.req.core.structure.RequirementsChunk"));
          }
          @Override
          public Class getOutputType() {
            return SNode.class;
          }
          @Override
          public Boolean loadLazy(ViewElement<SNode> element) {
            Project mpsProject = element.getProject();
            return false;
          }

        });
        addElement(new AbstractViewElementDescriptor<SNode>() {
          @Override
          public ElementId getExtendsId() {
            return new ElementId("requirement", new ViewId("org.iets3.req.plugin.plugin.RequirementsExplorer"));
          }
          @Override
          public ElementId getParentId() {
            return new ElementId("requirement", new ViewId("org.iets3.req.plugin.plugin.RequirementsExplorer"));
          }
          @Override
          public boolean isAbstract() {
            return false;
          }
          @Override
          public boolean isOverride() {
            return false;
          }
          @Override
          public Iterable<ViewElement<SNode>> queryElements(final Project mpsProject, final ViewElement parentElement, final ViewId contextView) {
            final ElementId descriptorId = new ElementId("requirementChildren", new ViewId("org.iets3.req.plugin.plugin.RequirementsExplorer"));
            ViewElement element = parentElement;
            Object queryResult = ListSequence.fromList(SLinkOperations.getChildren(((SNode) element.getObject(new ElementId("requirement", new ViewId("org.iets3.req.plugin.plugin.RequirementsExplorer")))), MetaAdapterFactory.getContainmentLink(0xa3c6f64241b744cbL, 0x951b463b8427a245L, 0x477d8ab2bc87c94fL, 0x477d8ab2bc87c9a5L, "requirements"))).where(new IWhereFilter<SNode>() {
              public boolean accept(SNode it) {
                return !(SNodeOperations.isInstanceOf(it, MetaAdapterFactory.getInterfaceConcept(0xd4280a54f6df4383L, 0xaa41d1b2bffa7eb1L, 0xe900768cf47dcc3L, "com.mbeddr.core.base.structure.IEmpty")));
              }
            });

            Iterable<SNode> rawSequence = (queryResult instanceof Iterable ? ((Iterable<SNode>) queryResult) : Sequence.<SNode>singleton(((SNode) queryResult)));

            return Sequence.fromIterable(rawSequence).where(new IWhereFilter<SNode>() {
              public boolean accept(SNode it) {
                return it != null;
              }
            }).select(new ISelector<SNode, ViewElement<SNode>>() {
              public ViewElement<SNode> select(SNode it) {
                return new ViewElement<SNode>(it, descriptorId, mpsProject, parentElement, contextView);
              }
            });
          }
          @Override
          public ElementId getId() {
            return new ElementId("requirementChildren", new ViewId("org.iets3.req.plugin.plugin.RequirementsExplorer"));
          }
          @Override
          public Class getOutputType() {
            return SNode.class;
          }

        });
        addElement(new AbstractViewElementDescriptor<SNode>() {
          @Override
          public ElementId getParentId() {
            return new ElementId("requirementsModule", new ViewId("org.iets3.req.plugin.plugin.RequirementsExplorer"));
          }
          @Override
          public String getLabel(ViewElement element) {
            return SPropertyOperations.getString(((SNode) element.getObject(new ElementId("requirement", new ViewId("org.iets3.req.plugin.plugin.RequirementsExplorer")))), MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"));
          }
          @Override
          public boolean isAbstract() {
            return false;
          }
          @Override
          public boolean isOverride() {
            return false;
          }
          @Override
          public Iterable<ViewElement<SNode>> queryElements(final Project mpsProject, final ViewElement parentElement, final ViewId contextView) {
            final ElementId descriptorId = new ElementId("requirement", new ViewId("org.iets3.req.plugin.plugin.RequirementsExplorer"));
            ViewElement element = parentElement;
            Object queryResult = ListSequence.fromList(SLinkOperations.getChildren(((SNode) element.getObject(new ElementId("requirementsModule", new ViewId("org.iets3.req.plugin.plugin.RequirementsExplorer")))), MetaAdapterFactory.getContainmentLink(0xa3c6f64241b744cbL, 0x951b463b8427a245L, 0x477d8ab2bc87c94fL, 0x477d8ab2bc87c9a5L, "requirements"))).where(new IWhereFilter<SNode>() {
              public boolean accept(SNode it) {
                return !(SNodeOperations.isInstanceOf(it, MetaAdapterFactory.getInterfaceConcept(0xd4280a54f6df4383L, 0xaa41d1b2bffa7eb1L, 0xe900768cf47dcc3L, "com.mbeddr.core.base.structure.IEmpty")));
              }
            });

            Iterable<SNode> rawSequence = (queryResult instanceof Iterable ? ((Iterable<SNode>) queryResult) : Sequence.<SNode>singleton(((SNode) queryResult)));

            return Sequence.fromIterable(rawSequence).where(new IWhereFilter<SNode>() {
              public boolean accept(SNode it) {
                return it != null;
              }
            }).select(new ISelector<SNode, ViewElement<SNode>>() {
              public ViewElement<SNode> select(SNode it) {
                return new ViewElement<SNode>(it, descriptorId, mpsProject, parentElement, contextView);
              }
            });
          }
          @Override
          public ElementId getId() {
            return new ElementId("requirement", new ViewId("org.iets3.req.plugin.plugin.RequirementsExplorer"));
          }
          @Nullable
          @Override
          public Icon getIcon(ViewElement element) {
            return IconManager.getIconFor(((SNode) element.getObject(new ElementId("requirement", new ViewId("org.iets3.req.plugin.plugin.RequirementsExplorer")))));
          }
          @Override
          public String getActionGroupId(ViewElement element) {
            return reqActions_ActionGroup.ID;
          }
          @Override
          public boolean isAssignable(Project mpsProject, ViewElement<SNode> element) {
            return super.isAssignable(mpsProject, element) && SNodeOperations.isInstanceOf(element.getObject(), MetaAdapterFactory.getConcept(0xa3c6f64241b744cbL, 0x951b463b8427a245L, 0x477d8ab2bc8195aeL, "org.iets3.req.core.structure.AbstractRequirement"));
          }
          @Override
          public Class getOutputType() {
            return SNode.class;
          }
          @Override
          public Boolean loadLazy(ViewElement<SNode> element) {
            Project mpsProject = element.getProject();
            return false;
          }

        });

      }

      public void addElement(IViewElementDescriptor element) {
        MapSequence.fromMap(myElements).put(element.getId(), element);
      }

      protected ViewId getViewId() {
        return getId();
      }

      @Override
      public ViewId getId() {
        return new ViewId("org.iets3.req.plugin.plugin.RequirementsExplorer");
      }
      @Override
      public ViewId getExtendsId() {
        return new ViewId("org.iets3.core.plugin.plugin.SpecExplorer");
      }
      @Override
      public List<IViewElementDescriptor> getElements() {
        return Sequence.fromIterable(MapSequence.fromMap(myElements).values()).toListSequence();
      }
      @Override
      public IViewElementDescriptor getElement(ElementId id) {
        return MapSequence.fromMap(myElements).get(id);
      }
      @Override
      public int getPriority() {
        return 5;
      }
    });
  }

  @Override
  public Iterable<IViewDescriptor> getViewDescriptors() {
    return myViews;
  }
}
