package org.iets3.req.plugin.plugin;

/*Generated by MPS */

import jetbrains.mps.plugins.actions.GeneratedActionGroup;

public class reqActions_ActionGroup extends GeneratedActionGroup {
  public static final String ID = "org.iets3.req.plugin.plugin.reqActions_ActionGroup";
  public reqActions_ActionGroup() {
    super("reqActions", ID);
    this.setIsInternal(false);
    this.setPopup(false);
    reqActions_ActionGroup.this.addAction("org.iets3.req.plugin.plugin.DeleteRequirement_Action");
    reqActions_ActionGroup.this.addSeparator();
    reqActions_ActionGroup.this.addAction("org.iets3.req.plugin.plugin.NewReqActionInModule_Action");
    reqActions_ActionGroup.this.addSeparator();
    reqActions_ActionGroup.this.addAction("org.iets3.req.plugin.plugin.NewModuleOnModel_Action");
  }
}
