package org.iets3.req.plugin.plugin;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;
import org.jetbrains.mps.openapi.model.SModel;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SModelOperations;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import jetbrains.mps.internal.collections.runtime.ISelector;
import jetbrains.mps.lang.core.behavior.BaseConcept__BehaviorDescriptor;

public class RequirementsExplorerHelper {

  public static Iterable<SNode> getReqChunks(SModel model) {
    return ListSequence.fromList(SModelOperations.roots(model, MetaAdapterFactory.getConcept(0xa3c6f64241b744cbL, 0x951b463b8427a245L, 0x477d8ab2bc81949cL, "org.iets3.req.core.structure.RequirementsChunk"))).sort(new ISelector<SNode, String>() {
      public String select(SNode it) {
        return (String) BaseConcept__BehaviorDescriptor.getPresentation_idhEwIMiw.invoke(it);
      }
    }, true);
  }

}
