package org.iets3.req.plugin.plugin;

/*Generated by MPS */

import com.mbeddr.mpsutil.refactoring.rt.util.EditorHintToggleAction;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class TogglerequirementsAsTables extends EditorHintToggleAction {

  public TogglerequirementsAsTables() {
    super("Requirements Table");
  }

  protected String getHintID() {
    return "org.iets3.req.core.editor.requirementsHints.table";
  }
  protected SNode getRequiredConcept() {
    return MetaAdapterFactory.getConcept(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL, "jetbrains.mps.lang.core.structure.BaseConcept").getDeclarationNode();
  }
}
