package org.iets3.req.core.actions;

/*Generated by MPS */

import jetbrains.mps.openapi.actions.descriptor.NodeFactory;
import org.jetbrains.mps.openapi.model.SNode;
import org.jetbrains.mps.openapi.model.SModel;
import java.util.List;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;

public class GenerateUniqueID {
  public static class NodeFactory_816340308089925200 implements NodeFactory {
    public void setup(SNode newNode, SNode sampleNode, SNode enclosingNode, SModel model) {
      List<SNode> allreqs;
      allreqs = SNodeOperations.getNodeDescendants(SNodeOperations.getContainingRoot(enclosingNode), MetaAdapterFactory.getConcept(0xa3c6f64241b744cbL, 0x951b463b8427a245L, 0x477d8ab2bc8195aeL, "org.iets3.req.core.structure.AbstractRequirement"), false, new SAbstractConcept[]{});
      int maxID;
      maxID = 0;
      for (SNode req : ListSequence.fromList(allreqs)) {
        if (SPropertyOperations.getInteger(req, MetaAdapterFactory.getProperty(0xa3c6f64241b744cbL, 0x951b463b8427a245L, 0x477d8ab2bc8195aeL, 0xb54392f5f8273cdL, "uniqueID")) > maxID) {
          maxID = SPropertyOperations.getInteger(req, MetaAdapterFactory.getProperty(0xa3c6f64241b744cbL, 0x951b463b8427a245L, 0x477d8ab2bc8195aeL, 0xb54392f5f8273cdL, "uniqueID"));
        }
      }
      SPropertyOperations.set(newNode, MetaAdapterFactory.getProperty(0xa3c6f64241b744cbL, 0x951b463b8427a245L, 0x477d8ab2bc8195aeL, 0xb54392f5f8273cdL, "uniqueID"), "" + (maxID + 1));
    }
  }
}
