package org.iets3.glossary.typesystem;

/*Generated by MPS */

import jetbrains.mps.errors.QuickFix_Runtime;
import jetbrains.mps.smodel.SNodePointer;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class addBackReference_QuickFix extends QuickFix_Runtime {
  public addBackReference_QuickFix() {
    super(new SNodePointer("r:4478be3d-ebce-4458-9928-521ecca4fead(org.iets3.glossary.typesystem)", "7551038907536765081"));
  }
  public String getDescription(SNode node) {
    return "Add Back Reference";
  }
  public void execute(SNode node) {
    SNode copy = SNodeOperations.copyNode(((SNode) addBackReference_QuickFix.this.getField("theOneThatExists")[0]));
    ListSequence.fromList(SLinkOperations.getChildren(((SNode) addBackReference_QuickFix.this.getField("theOneThatMissesIt")[0]), MetaAdapterFactory.getContainmentLink(0x8e4e17debc104a34L, 0xa376a243fbde540eL, 0x68caade118d74a57L, 0x68caade118d895ceL, "attrs"))).addElement(copy);
    SLinkOperations.setTarget(copy, MetaAdapterFactory.getReferenceLink(0x8e4e17debc104a34L, 0xa376a243fbde540eL, 0x68caade118e05b79L, 0x68caade118e05b7aL, "term"), SNodeOperations.cast(SNodeOperations.getParent(((SNode) addBackReference_QuickFix.this.getField("theOneThatExists")[0])), MetaAdapterFactory.getConcept(0x8e4e17debc104a34L, 0xa376a243fbde540eL, 0x68caade118d74a57L, "org.iets3.glossary.structure.GlossaryTerm")));
  }
}
